# Generated by Django 5.1.3 on 2024-11-09 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Festival',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('fecha', models.DateField()),
                ('ubicacion', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=6)),
                ('foto', models.ImageField(upload_to='festivales/')),
            ],
        ),
        migrations.CreateModel(
            name='Promotor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('pais', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
                ('foto', models.ImageField(upload_to='promotores/')),
            ],
        ),
        migrations.CreateModel(
            name='Interprete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('info_general', models.TextField()),
                ('pais', models.CharField(max_length=50)),
                ('genero_musica', models.CharField(max_length=50)),
                ('foto', models.ImageField(upload_to='interpretes/')),
                ('festivales', models.ManyToManyField(blank=True, related_name='interpretes_en_interprete', to='app1.festival')),
            ],
        ),
        migrations.AddField(
            model_name='festival',
            name='interpretes',
            field=models.ManyToManyField(blank=True, related_name='festivales_en_festival', to='app1.interprete'),
        ),
        migrations.AddField(
            model_name='festival',
            name='promotor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='festivales', to='app1.promotor'),
        ),
    ]
