# Generated by Django 5.1.3 on 2024-11-14 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='festival',
            name='foto',
            field=models.ImageField(upload_to='static/media/festivales/'),
        ),
        migrations.CreateModel(
            name='FestivalInterprete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_participacion', models.DateField(blank=True, null=True)),
                ('festival', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.festival')),
                ('interprete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.interprete')),
            ],
        ),
    ]
