# Generated by Django 5.1.3 on 2024-12-05 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_festival_entradasdisponibles_interprete_fotofondo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=15)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('localidad', models.CharField(blank=True, max_length=100, null=True)),
                ('numEntradas', models.PositiveIntegerField()),
                ('fechaReserva', models.DateTimeField(auto_now_add=True)),
                ('festival', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='app1.festival')),
            ],
        ),
    ]
