# Generated by Django 5.1.3 on 2024-12-05 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_reserva'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='reserva',
            table='app1_reservas',
        ),
    ]
