# Generated by Django 5.1.3 on 2024-12-05 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_alter_reserva_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='festival',
            name='fotoFondo',
            field=models.ImageField(default=2, upload_to='festivales/'),
            preserve_default=False,
        ),
    ]
